Debug RTD PR preview build

diff --git a/.github/workflows/rtd-pr-preview.yml b/.github/workflows/rtd-pr-preview.yml
--- a/.github/workflows/rtd-pr-preview.yml
+++ b/.github/workflows/rtd-pr-preview.yml
@@ -14,6 +14,22 @@ permissions:
 
 jobs:
   documentation-links:
+    post_checkout:
+      # Cancel building pull requests when there aren't changes in the docs directory or YAML file.
+      # You can add any other files or directories that you'd like here as well,
+      # like your docs requirements file, or other files that will change your docs build.
+      #
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - echo "========"
+      - echo "$READTHEDOCS_VERSION_TYPE"
+      - echo "git diff --quiet origin/main -- docs/ .readthedocs.yaml requirements-docs.txt packages/volto/.storybook"
+      - echo "========"
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml requirements-docs.txt packages/volto/.storybook;
+        then
+          exit 183;
+        fi
     runs-on: ubuntu-latest
     steps:
       - uses: readthedocs/actions/preview@v1
